#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/.local/bin/new-wall &
dunst &
xsetroot -cursor_name left_ptr &
#picom &

bspc monitor -d      

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating follow=on rectangle=500x300+1410+50
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a URxvt desktop='^1' follow=on
